# Generated by Django 2.0.2 on 2018-02-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_recognization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadDigit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.FileField(upload_to='images/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
