# Generated by Django 2.0.2 on 2018-02-04 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_recognization', '0002_uploaddigit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
